<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Recaptcha editar con fecha</name>
   <tag></tag>
   <elementGuidId>3b4ccefc-b1c0-4a21-9cea-449f3c288848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_trCaptcha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_trCaptcha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79306750-00e5-44c8-a26e-274c25f8c659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_trCaptcha</value>
      <webElementGuid>95bc5b27-f4ce-4e18-b2ac-7018a27beb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DivReCaptchaG</value>
      <webElementGuid>7dbb1fbe-607e-4b9a-8e57-bf2c44191cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_trCaptcha&quot;)</value>
      <webElementGuid>8d71b675-658b-4509-8aea-73e3efc07fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_trCaptcha']</value>
      <webElementGuid>ac70e99a-8c7b-4988-b249-ca75be8a8526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_uplContenido']/div/div[3]</value>
      <webElementGuid>78796595-5b46-46c5-b04b-5b56fc3a0c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de creación:'])[1]/following::div[1]</value>
      <webElementGuid>feb65797-06ca-4e11-86d9-58fc1f7bb038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activa'])[1]/following::div[1]</value>
      <webElementGuid>eb2680a5-dddc-4942-aeba-e193e3b01b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código de cita:'])[1]/preceding::div[6]</value>
      <webElementGuid>046129c4-ab5b-4b87-9707-77f3b24bec89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requisitos Mínimos:'])[1]/preceding::div[7]</value>
      <webElementGuid>a0709fdc-b6f2-435b-8fca-b7d6c95fdaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]</value>
      <webElementGuid>acf445f5-606d-4930-91b7-7748c7378b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl00_ContentPlaceHolder2_trCaptcha']</value>
      <webElementGuid>f8b259f3-4016-4b08-af74-bf069c3f8e5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
