<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Campo obligatorio_ctl00_ContentPlaceHolder2_recaptcha</name>
   <tag></tag>
   <elementGuidId>9660801d-9062-4941-bf82-c2ff310c770f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_recaptcha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_recaptcha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>88d5e5e7-ce53-4f00-ba1d-e812f0dda2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_recaptcha</value>
      <webElementGuid>0b11b030-efc4-468b-8cbf-01213cac4b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>g-recaptcha</value>
      <webElementGuid>f884dc3f-05bd-45c6-97eb-bb29a88e4fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sitekey</name>
      <type>Main</type>
      <value>6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI</value>
      <webElementGuid>f4ced4ec-5345-4a17-b95c-687906a2f1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_recaptcha&quot;)</value>
      <webElementGuid>8297bd54-97ee-4421-b40b-a0d8d9fa44e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_recaptcha']</value>
      <webElementGuid>b85d32b0-18b4-4dd8-b7dc-d9dc418d6eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_uplContenido']/div/div[3]/div</value>
      <webElementGuid>5cf6bd8b-23fe-41a4-90e6-a554e9eca6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campo obligatorio'])[11]/following::div[3]</value>
      <webElementGuid>d8a8f720-8ce8-4cb6-ac58-f52fb32b8b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[2]/following::div[6]</value>
      <webElementGuid>bfee034b-6c11-4312-90ef-b1d5c5f40ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::div[14]</value>
      <webElementGuid>829f9f23-960a-4054-9c03-576697c26a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div</value>
      <webElementGuid>c6756dd5-544f-48d2-949e-8b2c1ab5be08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl00_ContentPlaceHolder2_recaptcha']</value>
      <webElementGuid>47a5f83b-810c-445e-96b9-575697119d37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
