<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnVerDetalle2</name>
   <tag></tag>
   <elementGuidId>5eda9b35-c0f7-4ecc-9791-d958ad3f0703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_btnVerDetalle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_btnVerDetalle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e20e581-a268-4d7c-938a-8428752c6e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_btnVerDetalle</value>
      <webElementGuid>0b6fc14b-9701-4c7f-92fb-e3381c4daeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver detalle de la cita</value>
      <webElementGuid>beb3e7dc-e94b-41b6-8117-56eff2ba36d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnVerDetalleImg</value>
      <webElementGuid>aafebcc5-6cf7-4e79-aead-7de2bb505566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl03$btnVerDetalle','')</value>
      <webElementGuid>b238c10b-b0b3-4ce3-894f-74a20a2405e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_btnVerDetalle&quot;)</value>
      <webElementGuid>5e3df0fa-6e6b-4d82-a497-24916b319cc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_btnVerDetalle']</value>
      <webElementGuid>6d04b336-3aa4-4309-bda2-c616600993dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas']/tbody/tr[3]/td[10]/div/a</value>
      <webElementGuid>df8bce04-9011-4665-93c3-c48021f2e02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl03$btnVerDetalle','')&quot;)]</value>
      <webElementGuid>41e5d93a-cd22-49ec-bac8-32dc38deec2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[10]/div/a</value>
      <webElementGuid>1c4951db-a2cd-4810-9e33-8eb52f41de13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_btnVerDetalle' and @title = 'Ver detalle de la cita' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl03$btnVerDetalle&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>18c9eba3-0eb6-40fa-8df8-706c7658009e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
