<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnVerDetalle1</name>
   <tag></tag>
   <elementGuidId>90acdc1f-de1e-4784-b33f-1ceb36161aa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_btnVerDetalle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_btnVerDetalle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ff4ba724-a525-430e-9a21-c663b8af9038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_btnVerDetalle</value>
      <webElementGuid>e75031fc-787d-437e-bd07-1193d89ce187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver detalle de la cita</value>
      <webElementGuid>5f378700-6452-4e82-bf01-3fb288803948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnVerDetalleImg</value>
      <webElementGuid>58dcad8f-a2cc-47df-a570-b1c8bc61d058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl02$btnVerDetalle','')</value>
      <webElementGuid>799a3721-81da-4d50-a3d9-21b893929144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_btnVerDetalle&quot;)</value>
      <webElementGuid>ba7b25ba-f12f-4a60-9b09-699fd676689b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_btnVerDetalle']</value>
      <webElementGuid>fbb13e1d-9628-44bf-924b-0a82964b72eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas']/tbody/tr[2]/td[10]/div/a</value>
      <webElementGuid>9928e345-9b3f-41bd-b210-a5c35770c2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl02$btnVerDetalle','')&quot;)]</value>
      <webElementGuid>e8675c5f-323e-43f5-9542-99dea1643532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/a</value>
      <webElementGuid>a19dd2b9-1db5-4fa6-8e33-d00d6181a7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_btnVerDetalle' and @title = 'Ver detalle de la cita' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl02$btnVerDetalle&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>8a515528-31fa-4f3e-afdd-4c1099a3f1f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
