<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_ 1 Seleccionar</name>
   <tag></tag>
   <elementGuidId>7ff4cd94-fd92-4272-97e4-96c38dffcb03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_chkSeleccionar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_chkSeleccionar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31e711bc-81fd-4bd4-9243-086312b06520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_chkSeleccionar</value>
      <webElementGuid>1b7ef5c8-b489-4dcc-a895-0b0802d5993b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>51afa5a2-905f-4dbd-a36e-76c1c380df5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl02$chkSeleccionar</value>
      <webElementGuid>4af48c67-ff08-4e4d-a1d7-adb16cf68ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_chkSeleccionar&quot;)</value>
      <webElementGuid>2751c6f7-4b1f-47ec-b5cf-f65f2ab13a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_chkSeleccionar']</value>
      <webElementGuid>7913681d-6fb0-4d8f-9ce6-6482fd04c6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas']/tbody/tr[2]/td[12]/span/input</value>
      <webElementGuid>e328b84c-e23f-4284-9bd0-936a450931ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>4c0d43d9-9ee6-4f05-9430-72c5a0f74be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl02_chkSeleccionar' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl02$chkSeleccionar']</value>
      <webElementGuid>e90f5f0a-c6c1-491e-a341-23632828f7ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
