<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_3 Seleccionar</name>
   <tag></tag>
   <elementGuidId>f6106c93-4459-459b-abf4-b5fb49101d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl04_chkSeleccionar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl04_chkSeleccionar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a12002b-e40e-44bf-ae40-effe21aea897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl04_chkSeleccionar</value>
      <webElementGuid>5e969014-8d95-4b61-ac36-c7336f628e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b6a16fee-096b-4d9b-a33f-3d163dd462c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl04$chkSeleccionar</value>
      <webElementGuid>17a8c6b7-a2d0-4c5f-9eb6-868dbb2128f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl04_chkSeleccionar&quot;)</value>
      <webElementGuid>1343c53c-917d-4dc2-8c70-4518c885dc91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl04_chkSeleccionar']</value>
      <webElementGuid>af8ad409-7f1c-40e6-95d1-9a88eef016c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas']/tbody/tr[4]/td[12]/span/input</value>
      <webElementGuid>76f1f75b-afaf-4ac4-a2b1-e682cca2696f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[12]/span/input</value>
      <webElementGuid>013c9027-6c92-49d4-a222-3cd2e0f546e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl04_chkSeleccionar' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl04$chkSeleccionar']</value>
      <webElementGuid>1bd9bc95-4d5b-45b8-a818-ecf76ce5618e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
