<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_2 Seleccionar</name>
   <tag></tag>
   <elementGuidId>8576b2df-3c93-400e-ae54-31998d4873ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_chkSeleccionar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_chkSeleccionar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30f8a954-a122-47d3-aa4f-346dcd3da05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_chkSeleccionar</value>
      <webElementGuid>60a83b84-eaec-46a1-9690-0c4f6d3015c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1fdd3e93-753b-4874-a13f-a65366674411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl03$chkSeleccionar</value>
      <webElementGuid>2551f5a8-d84a-47dc-b6a3-5bab832ebc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_chkSeleccionar&quot;)</value>
      <webElementGuid>04fa60b2-2232-497b-ae37-041eb52530f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_chkSeleccionar']</value>
      <webElementGuid>e3237be4-f218-4d30-94ae-0ce8bd34d87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_gvCitasAbiertas']/tbody/tr[3]/td[12]/span/input</value>
      <webElementGuid>24d50736-63f6-4988-85cb-508c2d7c1c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[12]/span/input</value>
      <webElementGuid>bdceaa0a-6dba-474c-9c3c-c965bff591dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder2_gvCitasAbiertas_ctl03_chkSeleccionar' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder2$gvCitasAbiertas$ctl03$chkSeleccionar']</value>
      <webElementGuid>200e434f-6d45-4520-9cb0-11991c81b531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
