<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_X_ Cerrar Modal inicio</name>
   <tag></tag>
   <elementGuidId>53ba9b27-2265-4710-8edd-d360a8f09260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btnCerrar</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Cerrar' and (text() = 'X' or . = 'X')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='aspnetForm']/div[3]/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e98d9b0e-5db7-475b-b2dc-7a1512a77b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnCerrar</value>
      <webElementGuid>a2b4c70d-d2d7-406a-9dc6-ddaf32c484d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cerrar</value>
      <webElementGuid>a1a2907e-f4f9-49ba-8c93-f4b6c7348229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>c74c18ca-8272-4da7-9274-d73f613bebb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aspnetForm&quot;)/div[@class=&quot;divEnvoltura&quot;]/div[@class=&quot;divModal&quot;]/a[@class=&quot;btnCerrar&quot;]</value>
      <webElementGuid>3a4cbb69-a960-4c40-9a88-75a50c9a5110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/div[4]/a</value>
      <webElementGuid>2810fe6a-74c8-4b1e-b054-47efaea0bd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'X')]</value>
      <webElementGuid>15675df0-08b9-4a82-a386-79a9303a9d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hora'])[1]/following::a[1]</value>
      <webElementGuid>9c3252e9-0c8b-4ee2-b681-933687436947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='día'])[1]/following::a[1]</value>
      <webElementGuid>4598bc5f-0b0d-4ca5-8e64-9eec8edc8334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selección de cita'])[1]/preceding::a[4]</value>
      <webElementGuid>dd8e6f46-e0b4-4322-9f67-868b52bbd99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre Ciudadano/Cliente:'])[1]/preceding::a[4]</value>
      <webElementGuid>959a5def-a00b-4bba-bb93-e3cd4bf33208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>e3bd41a0-9fe6-42c6-963e-d55e21d08f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>a2cbd704-1746-45be-8bc9-a2cda2448955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Cerrar' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>db436610-0b32-4c19-a5d4-ef263484c38c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
