<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_X_cerrar Modal Inicio2</name>
   <tag></tag>
   <elementGuidId>f7333580-b590-4f69-94ac-c5e6776ad38e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cerrar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='javascript:VentanaModal.Ocultar();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b23ba1d8-dbc1-495f-afb8-2bf3c657d5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cerrar</value>
      <webElementGuid>eb92109a-2ce4-4e59-bcb0-9d0aca483a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cerrar</value>
      <webElementGuid>4ad2a4d2-c89e-46b9-8374-45795ce16e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:VentanaModal.Ocultar();</value>
      <webElementGuid>429a3942-e965-435b-829d-9cd1954c550c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divVentanaModal&quot;)/div[@class=&quot;ventanaModalEnvoltura cajaMover ui-draggable&quot;]/div[@class=&quot;ventanaModalTitulo&quot;]/div[@class=&quot;ventanaModalTituloHerramientas&quot;]/a[@class=&quot;cerrar&quot;]</value>
      <webElementGuid>3fc54594-f59a-4cac-8e3c-747b89fd64bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='javascript:VentanaModal.Ocultar();']</value>
      <webElementGuid>96cd0155-d6d4-4404-a0bf-8a3a63980e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divVentanaModal']/div[2]/div/div/a[3]</value>
      <webElementGuid>5b91f647-c927-4efd-85fb-9ddb340ef19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>87652c20-d59b-4b06-8895-7b2fb68e0816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Cerrar']</value>
      <webElementGuid>df694f7e-8dfc-4272-9524-295d1144c2b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
