<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Hora3</name>
   <tag></tag>
   <elementGuidId>53d5f6b4-a81e-4448-a6ce-05d4be3e2097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl04_imgSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl04_imgSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56890408-90a0-4124-b227-a4b63c90b53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>75b8e1cc-72c3-4089-bd3f-0b808ebfaf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl04$imgSeleccionar</value>
      <webElementGuid>49df276b-837e-4b0e-84c8-2245165f6f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl04_imgSeleccionar</value>
      <webElementGuid>20f7cc99-00a4-459a-a887-f21b3bd0402f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click para seleccionar la cita ...</value>
      <webElementGuid>fc7469fa-aefe-4f52-8b94-f43aa7bcc8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Recursos/img/ico/echo01.png</value>
      <webElementGuid>d31e20a8-d903-4938-8ee2-39a0b8169c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl04_imgSeleccionar&quot;)</value>
      <webElementGuid>a145b345-276b-4e6a-827b-b0b64456a5bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl04_imgSeleccionar']</value>
      <webElementGuid>8490fb42-ee9b-49cf-a32e-164ddc482977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles']/tbody/tr[4]/td[3]/input</value>
      <webElementGuid>a43f52ce-e0a7-4415-9f45-3335d58bc74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/input</value>
      <webElementGuid>f5240830-3f09-470b-8e40-b6cece52481c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl04$imgSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl04_imgSeleccionar' and @title = 'Click para seleccionar la cita ...' and @src = 'Recursos/img/ico/echo01.png']</value>
      <webElementGuid>e3aa70a8-4657-4bd3-8574-8593fb70fcf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
