<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Hora2</name>
   <tag></tag>
   <elementGuidId>6f5422ef-7fa1-42d1-96cb-f4844da848a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl03_imgSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl03_imgSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf693042-8243-4a9a-a659-6554cbb1c1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>829e8ed6-6d43-42bf-adcc-16119211c947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl03$imgSeleccionar</value>
      <webElementGuid>79c7abe9-c771-430f-ac33-f9c79c48dc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl03_imgSeleccionar</value>
      <webElementGuid>1fd1323c-ebbe-47bc-b946-2a18fad067f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click para seleccionar la cita ...</value>
      <webElementGuid>491b3014-9100-42dd-a7c0-11042ab56b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Recursos/img/ico/echo01.png</value>
      <webElementGuid>ecc2d4de-38ef-464f-a87b-ebc0c4c64637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl03_imgSeleccionar&quot;)</value>
      <webElementGuid>15f87fec-4151-4a5e-b3c4-0132b99b43ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl03_imgSeleccionar']</value>
      <webElementGuid>72ac942c-0ac0-486b-8147-66d369a60cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles']/tbody/tr[3]/td[3]/input</value>
      <webElementGuid>1cb94e34-7faa-4643-9630-2f8900df08d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input</value>
      <webElementGuid>79a212ec-3695-4f0e-b189-6a49f93b847a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl03$imgSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl03_imgSeleccionar' and @title = 'Click para seleccionar la cita ...' and @src = 'Recursos/img/ico/echo01.png']</value>
      <webElementGuid>ca1704ff-4140-40cd-9be6-24db868f29f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
