<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Hora4</name>
   <tag></tag>
   <elementGuidId>7d6c6b58-23e4-48b7-92df-4dd407812dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl05_imgSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl05_imgSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cebf63a2-9eef-474b-b7af-8de38c4ed3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>9b3a0f72-499e-4068-9725-ac6fbfd461c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl05$imgSeleccionar</value>
      <webElementGuid>612ec6a8-4815-4917-a711-2a859e0e5e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl05_imgSeleccionar</value>
      <webElementGuid>bec55ca2-a995-498a-bcf2-1b62438d366f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click para seleccionar la cita ...</value>
      <webElementGuid>b4882257-6204-44a8-9d16-4201f91e4de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Recursos/img/ico/echo01.png</value>
      <webElementGuid>f6ef79c1-b432-48b2-9d04-e2c494c346e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl05_imgSeleccionar&quot;)</value>
      <webElementGuid>1891c034-9a57-4c0b-98cf-c3f652d9bb44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl05_imgSeleccionar']</value>
      <webElementGuid>251c66f8-bb4a-4078-9d7f-cee3b1369146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles']/tbody/tr[5]/td[3]/input</value>
      <webElementGuid>32e58ac0-766f-427e-acaf-d1e610b8e6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/input</value>
      <webElementGuid>6025a6fa-649e-4301-a49a-3a62165f85e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl05$imgSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl05_imgSeleccionar' and @title = 'Click para seleccionar la cita ...' and @src = 'Recursos/img/ico/echo01.png']</value>
      <webElementGuid>c5005fc9-b8ea-4c51-9394-d8eabd24fcd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
