<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Hora1</name>
   <tag></tag>
   <elementGuidId>ac561c11-5eb3-4557-af86-eea4737f05e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl02_imgSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl02_imgSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c44773c-a5a5-44cc-9d70-6901ca42f15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>a9e68ba1-9d03-42db-aafa-24d7963506da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl02$imgSeleccionar</value>
      <webElementGuid>722b6c08-d86f-49db-9d4a-9476ae2c42d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl02_imgSeleccionar</value>
      <webElementGuid>951951e5-001a-462b-89da-3b4188bf69f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click para seleccionar la cita ...</value>
      <webElementGuid>efcc3b3d-f657-4579-aadb-7b1ba702a33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Recursos/img/ico/echo01.png</value>
      <webElementGuid>255274e8-dfab-4ce1-98f3-06e346f2b48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl02_imgSeleccionar&quot;)</value>
      <webElementGuid>2b1d4cf4-dc57-4619-8fb6-561b73ffa286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl02_imgSeleccionar']</value>
      <webElementGuid>586c2311-1c87-478a-a07a-e149eabf6d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles']/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>6997a0ed-35c5-4fa9-b7cd-1722b05b88d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>039bacaa-c982-4ec8-9d7f-5dc9cccad099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl02$imgSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl02_imgSeleccionar' and @title = 'Click para seleccionar la cita ...' and @src = 'Recursos/img/ico/echo01.png']</value>
      <webElementGuid>9cf90caa-7b7a-4c6a-8476-59fc410081ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
