<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Hora5</name>
   <tag></tag>
   <elementGuidId>49d84997-4742-4fcc-bc3b-b2450ca313e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl06_imgSeleccionar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl06_imgSeleccionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71aacbf7-5d1d-42e0-a3e4-07bacd7f8504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>46d0edf6-caa1-43bb-acb8-97b4d79455dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl06$imgSeleccionar</value>
      <webElementGuid>40a3871c-0597-4ed7-8132-643487faaf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl06_imgSeleccionar</value>
      <webElementGuid>455cdd0f-5be7-460c-9ff8-487737dd758c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click para seleccionar la cita ...</value>
      <webElementGuid>582a79b1-bf53-4b02-a780-03f1b6a46566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Recursos/img/ico/echo01.png</value>
      <webElementGuid>3a8a8ebb-4003-46c8-9b1a-208b5e41283d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl06_imgSeleccionar&quot;)</value>
      <webElementGuid>567ec925-3eb1-40bb-bd12-e223e72df797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl06_imgSeleccionar']</value>
      <webElementGuid>920b2664-95ad-478a-a6de-e46202749dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder2_grdHorasDisponibles']/tbody/tr[6]/td[3]/input</value>
      <webElementGuid>1f4004d6-0608-4d3a-9de3-1e41fa126428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[3]/input</value>
      <webElementGuid>f1479b2a-edbc-4b4c-b6d9-8265538c7a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder2$grdHorasDisponibles$ctl06$imgSeleccionar' and @id = 'ctl00_ContentPlaceHolder2_grdHorasDisponibles_ctl06_imgSeleccionar' and @title = 'Click para seleccionar la cita ...' and @src = 'Recursos/img/ico/echo01.png']</value>
      <webElementGuid>01b32f7f-9c3b-4969-8e58-b8c2c4322f2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
