<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Ciudad</name>
   <tag></tag>
   <elementGuidId>bcc63582-8251-45ba-a47a-8fc935ad60a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_rcbCiudad_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_rcbCiudad_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23fd995a-7882-4a70-aeb8-5bbe14a35e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$rcbCiudad</value>
      <webElementGuid>3eaf3cca-d9cc-4c4e-bafc-7f66bf1fec55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f32da231-4237-4ce7-9259-52589a8fa53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbInput radPreventDecorate</value>
      <webElementGuid>ced31f44-33b8-454b-b656-e063f1b985ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_rcbCiudad_Input</value>
      <webElementGuid>913edefb-2595-440d-8c16-c79cf4c27b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-- Filtre o Seleccione --</value>
      <webElementGuid>eece4fb7-535f-4c5c-8ccf-3bb548c687a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2b6dd14b-9f74-48e9-9d21-381d061766a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_rcbCiudad_Input&quot;)</value>
      <webElementGuid>b2fe3104-72c5-4bf3-a050-2598607039c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_rcbCiudad_Input']</value>
      <webElementGuid>ea47e256-317b-4240-8ec3-f12d1975ee53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_rcbCiudad']/span/input</value>
      <webElementGuid>b03a4970-fc7f-4a00-865e-8ab47f09b15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[2]/div/div/span/input</value>
      <webElementGuid>7cbd0261-5ac1-4803-9527-3dbe1a62e4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$rcbCiudad' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_rcbCiudad_Input']</value>
      <webElementGuid>54764664-ff25-4da3-9aa2-494ac70923dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
