<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefono fijo</name>
   <tag></tag>
   <elementGuidId>82a2c199-95bf-49b3-b94f-45a380b6d1c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder2_txtTelefonoFijo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder2_txtTelefonoFijo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29b54f69-b968-4818-88a3-9a719cc843e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder2$txtTelefonoFijo</value>
      <webElementGuid>c597b2bb-a9f2-4c84-b521-bb78b0f3b50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b4a9ece-2858-4dc1-bfdc-f98ea296f5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>14414ea4-9499-4a4d-a448-6e38953de71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder2_txtTelefonoFijo</value>
      <webElementGuid>cbc95008-65b1-40eb-bb0e-1d436c1a0839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textoNumeros</value>
      <webElementGuid>a8cc2d43-c94d-4e16-9290-70ae18743bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2944f718-69f9-473d-b89c-90580ff06ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_txtTelefonoFijo&quot;)</value>
      <webElementGuid>b338cbe1-a148-44a5-a56c-679b7fb33b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder2_txtTelefonoFijo']</value>
      <webElementGuid>698c56c0-2f13-464d-99b9-303abb7f2134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder2_RowTelefonoFijo']/td[2]/input</value>
      <webElementGuid>ab3b5c89-9ece-426b-8836-f554454e4eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/input</value>
      <webElementGuid>8c0f076b-a6ed-4893-9a46-b1febdfe5206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder2$txtTelefonoFijo' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder2_txtTelefonoFijo']</value>
      <webElementGuid>943f50bf-d7d7-4ae1-883a-42bfb3aa8e63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
