<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_-- Filtre o Seleccione --(Departamento)</name>
   <tag></tag>
   <elementGuidId>6f226d86-12cf-4905-80d7-b6479dcd404a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_rcbDepartamento_DropDown']/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.rcbHovered</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>dbcb57e3-56a3-4a1d-87ba-066de983861b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbHovered</value>
      <webElementGuid>937d68d2-e407-4771-a174-72410ba41100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Filtre o Seleccione --</value>
      <webElementGuid>15ed740c-f84b-4bbf-82f7-37f9fe61a19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_rcbDepartamento_DropDown&quot;)/div[@class=&quot;rcbScroll rcbWidth&quot;]/ul[@class=&quot;rcbList&quot;]/li[@class=&quot;rcbHovered&quot;]</value>
      <webElementGuid>f3ed90ae-8ab2-429a-842a-9cc6f98385b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_rcbDepartamento_DropDown']/div/ul/li</value>
      <webElementGuid>b8086f7e-e828-47e3-aa57-c8d9c6fe4370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antioquia'])[1]/preceding::li[1]</value>
      <webElementGuid>30e87b67-3068-4bb6-ac75-ba689c92bb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bolivar'])[1]/preceding::li[2]</value>
      <webElementGuid>b5e4e248-0581-41aa-9fa2-2c7eacfd91d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-- Filtre o Seleccione --']/parent::*</value>
      <webElementGuid>2a513047-e811-4a54-82ca-0fe6b7069753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>f3852627-a140-4369-b871-0effcac85e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '-- Filtre o Seleccione --' or . = '-- Filtre o Seleccione --')]</value>
      <webElementGuid>ed3773f3-95ec-4c8a-b172-88ecf73ec155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
