<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Bolivar</name>
   <tag></tag>
   <elementGuidId>fc6faf96-ccb2-4cf5-9a55-7193c1e57a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolder2_rcbDepartamento_DropDown']/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.rcbHovered</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>55771d49-a808-48ee-b288-4a3c08aa3314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbHovered</value>
      <webElementGuid>759fa478-0f39-41ee-90e3-bd33b9dee055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bolivar</value>
      <webElementGuid>15569e6e-dbd1-4f5e-abc1-8726b2b2511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder2_rcbDepartamento_DropDown&quot;)/div[@class=&quot;rcbScroll rcbWidth&quot;]/ul[@class=&quot;rcbList&quot;]/li[@class=&quot;rcbHovered&quot;]</value>
      <webElementGuid>23195b0c-f01d-4b27-a42f-aeb861431f53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder2_rcbDepartamento_DropDown']/div/ul/li[3]</value>
      <webElementGuid>430263f7-0797-4cec-b706-bfa6290f7701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antioquia'])[1]/following::li[1]</value>
      <webElementGuid>95e746a0-3f3d-446c-95e2-6e529eeb231c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Filtre o Seleccione --'])[1]/following::li[2]</value>
      <webElementGuid>0ed46127-cb11-4043-bf03-584977156bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caldas'])[1]/preceding::li[1]</value>
      <webElementGuid>8eaa5643-7e52-44c6-a373-e0280826a8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cundinamarca'])[1]/preceding::li[2]</value>
      <webElementGuid>09bf041d-34fd-4e0f-a65b-443ac704a52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bolivar']/parent::*</value>
      <webElementGuid>696b26c6-21d6-4efe-893c-0f869289b913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>b655d74e-266e-4a2d-9121-48d8e23904a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Bolivar' or . = 'Bolivar')]</value>
      <webElementGuid>21a8227c-c781-4dd3-b568-0813ff643cec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
