<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Consulte Aqui Como Agendar su Cita</name>
   <tag></tag>
   <elementGuidId>35f75356-7e0c-442a-bef3-1160b1496c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btnInstrucciones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_uplContenido']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cf6f453-dbca-4a95-9393-bc99307f1a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnInstrucciones</value>
      <webElementGuid>21a7ba8a-a201-4635-8939-8e24cf75918a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.emtelco.co/agendamientoweb/app/webroot/img/Infografia_agendamiento.pdf</value>
      <webElementGuid>07856aa4-24d3-440e-afc5-035e605cd57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>34b03ef8-59c2-4d2e-94ae-4824a3bb04c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consulte Aquí Cómo Agendar su Cita</value>
      <webElementGuid>eb387cf7-6b86-4871-b488-f40d9b9fab51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_uplContenido&quot;)/div[@class=&quot;divCuerpoInicio col-xs-10 col-xs-offset-1&quot;]/a[@class=&quot;btnInstrucciones&quot;]</value>
      <webElementGuid>d9461242-d28a-4870-b06d-bd13024ccdc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_uplContenido']/div/a</value>
      <webElementGuid>1a1b0d82-f896-48ed-b797-1931aa21c80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Consulte Aquí Cómo Agendar su Cita')]</value>
      <webElementGuid>79af9a4a-8093-4b27-af7b-c575edcf15ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Novedades'])[1]/following::a[1]</value>
      <webElementGuid>64512b15-9542-460c-a0ab-b8d9e105285f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trámites que usted podrá agendar'])[1]/following::a[1]</value>
      <webElementGuid>a20c3644-f571-44ce-b648-29349129e7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::a[1]</value>
      <webElementGuid>fb6b9f4b-d7b0-4dc1-b715-a99d7e09d192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consulte Aquí Cómo Agendar su Cita']/parent::*</value>
      <webElementGuid>76a854d9-b420-466c-a3cc-7aa51b45c0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.emtelco.co/agendamientoweb/app/webroot/img/Infografia_agendamiento.pdf']</value>
      <webElementGuid>e9127737-3ac9-412f-b5f1-0a758454170e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a</value>
      <webElementGuid>a3b6c230-b60a-4259-a210-7f06c9fe109d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.emtelco.co/agendamientoweb/app/webroot/img/Infografia_agendamiento.pdf' and (text() = 'Consulte Aquí Cómo Agendar su Cita' or . = 'Consulte Aquí Cómo Agendar su Cita')]</value>
      <webElementGuid>0f0ab480-f642-4cac-9ab5-1e635b38ebe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
